// Auto-generated by `pnpm -C scripts cli performance` — do not edit.
export const locales = [
  {
    code: 'en',
    iso: 'en_US',
  },
  {
    code: 'de',
    iso: 'de_DE',
  },
  {
    code: 'ru',
    iso: 'ru_RU',
  },
  {
    code: 'fr',
    iso: 'fr_FR',
  },
]
