import { globby } from 'globby'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { flattenKeys } from './parser'

export interface GeneratorOptions {
  srcDir: string
  translationDir: string
  outputFile?: string // Where to place d.ts file
}

/**
 * Generates string with TypeScript types for translation keys.
 * Does not write file, only returns content.
 *
 * @param options - Generator options
 * @returns String with .d.ts file content
 */
export async function getTypesString(options: GeneratorOptions): Promise<string> {
  const localesDir = resolve(options.srcDir, options.translationDir)

  // Find all json files in translations folder (including pages subfolders)
  const files = await globby('**/*.json', {
    cwd: localesDir,
    absolute: true,
    ignore: ['node_modules/**', 'dist/**', '.nuxt/**'],
  })

  const allKeys = new Set<string>()

  for (const file of files) {
    try {
      const content = JSON.parse(readFileSync(file, 'utf-8'))
      const keys = flattenKeys(content)
      for (const k of keys) {
        allKeys.add(k)
      }
    }
    catch (e) {
      console.warn(`[i18n-types] Failed to parse ${file}:`, e)
    }
  }

  // Generate .d.ts file content
  // Important: we extend '@i18n-micro/types' module
  const keysContent = Array.from(allKeys)
    .sort()
    .map(key => `    '${key}': string;`)
    .join('\n')

  return `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @i18n-micro/types-generator
// DO NOT EDIT THIS FILE MANUALLY

import '@i18n-micro/types';

declare module '@i18n-micro/types' {
  export interface DefineLocaleMessage {
${keysContent}
  }
}
`
}

/**
 * Generates TypeScript types for translation keys from JSON files.
 * Writes result to file.
 *
 * @param options - Generator options
 * @returns Path to generated file
 */
export async function generateTypes(options: GeneratorOptions): Promise<string> {
  const fileContent = await getTypesString(options)

  // Determine path for writing (default to root or .nuxt)
  const outputPath = options.outputFile || resolve(options.srcDir, 'i18n-micro.d.ts')

  // Create directory if it doesn't exist
  const outputDir = dirname(outputPath)
  try {
    mkdirSync(outputDir, { recursive: true })
  }
  catch {
    // Directory already exists
  }

  writeFileSync(outputPath, fileContent, 'utf-8')

  return outputPath
}
