packages:
  - 'packages/*'
  - 'packages/*/playground'
  - 'packages/*/playground-*'
  - 'client'
  - 'playground'
  - 'test/fixtures/**/*'

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
