// Auto-generated by `pnpm -C scripts cli performance` — do not edit.
export const locales = [
  {
    code: 'en',
    language: 'en-US',
    file: 'en.json',
  },
  {
    code: 'de',
    language: 'de-DE',
    file: 'de.json',
  },
  {
    code: 'ru',
    language: 'ru-RU',
    file: 'ru.json',
  },
  {
    code: 'fr',
    language: 'fr-FR',
    file: 'fr.json',
  },
]
