import { execSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { repoRoot } from '../utils/workspace'
import { fixtureAbsDir, localesForNuxtConfig, type PerfFixtureDef } from './fixtures'
import type { PerfRuntimeProfile } from './types'

export const PERF_SHARED_DIR = join(repoRoot, 'test/fixtures/perf-shared')
export const RUNTIME_JSON = join(PERF_SHARED_DIR, 'runtime.json')

/** Write runtime profile consumed by fixture `generate.mjs` scripts. */
export function writeRuntimeProfile(profile: PerfRuntimeProfile): void {
  if (!existsSync(PERF_SHARED_DIR)) mkdirSync(PERF_SHARED_DIR, { recursive: true })
  writeFileSync(RUNTIME_JSON, `${JSON.stringify(profile, null, 2)}\n`)
  console.log(`Wrote ${RUNTIME_JSON}`)
}

/** Generated locale lists imported by fixture nuxt.config.ts files (from PERF_FIXTURES.localesFile). */
export function writePerfLocales(profile: PerfRuntimeProfile, fixtures: PerfFixtureDef[]): void {
  for (const fixture of fixtures) {
    if (!fixture.localesFile) continue
    const path = join(fixtureAbsDir(fixture), 'perf-locales.mjs')
    const locales = localesForNuxtConfig(fixture.localesFile, profile.locales)
    writeFileSync(
      path,
      `// Auto-generated by \`pnpm -C scripts cli performance\` — do not edit.\nexport const locales = ${JSON.stringify(locales, null, 2)}\n`,
    )
    console.log(`Wrote ${path}`)
  }
}

/** Regenerate dictionaries via each fixture's `generate:locales`. */
export function regenerateLocales(fixtures: PerfFixtureDef[]): void {
  for (const fixture of fixtures) {
    const cwd = fixtureAbsDir(fixture)
    console.log(`Generating locales for ${fixture.id}...`)
    execSync('pnpm run generate:locales', { cwd, stdio: 'inherit' })
  }
}
