import { createHash } from 'node:crypto'
import { execSync } from 'node:child_process'
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { repoRoot } from '../utils/workspace'
import { fixtureAbsDir, fixtureSourceAbsDir, localesForNuxtConfig, type PerfFixtureDef } from './fixtures'
import type { PerfRuntimeProfile } from './types'

export const PERF_SHARED_DIR = join(repoRoot, 'test/fixtures/perf-shared')
export const RUNTIME_JSON = join(PERF_SHARED_DIR, 'runtime.json')
export const LOCALE_FINGERPRINT = join(PERF_SHARED_DIR, '.locale-fingerprint')

export function profileFingerprint(profile: PerfRuntimeProfile): string {
  return createHash('sha1').update(JSON.stringify(profile)).digest('hex')
}

/** Write runtime profile consumed by fixture `generate.mjs` scripts. */
export function writeRuntimeProfile(profile: PerfRuntimeProfile): void {
  if (!existsSync(PERF_SHARED_DIR)) mkdirSync(PERF_SHARED_DIR, { recursive: true })
  writeFileSync(RUNTIME_JSON, `${JSON.stringify(profile, null, 2)}\n`)
  console.log(`Wrote ${RUNTIME_JSON}`)
}

/** Generated locale lists imported by fixture nuxt.config.ts files (from PERF_FIXTURES.localesFile). */
export function writePerfLocales(profile: PerfRuntimeProfile, fixtures: PerfFixtureDef[]): void {
  for (const fixture of fixtures) {
    if (!fixture.localesFile) continue
    const path = join(fixtureAbsDir(fixture), 'perf-locales.mjs')
    const locales = localesForNuxtConfig(fixture.localesFile, profile.locales)
    writeFileSync(
      path,
      `// Auto-generated by \`pnpm -C scripts cli performance\` — do not edit.\nexport const locales = ${JSON.stringify(locales, null, 2)}\n`,
    )
    console.log(`Wrote ${path}`)
  }
}

/** Regenerate dictionaries via each fixture's `generate:locales`. */
export function regenerateLocales(fixtures: PerfFixtureDef[]): void {
  for (const fixture of fixtures) {
    const cwd = fixtureAbsDir(fixture)
    console.log(`Generating locales for ${fixture.id}...`)
    execSync('pnpm run generate:locales', { cwd, stdio: 'inherit' })
  }
}

/** True when `dir` exists and contains at least one `.json` file (non-recursive). */
export function dirHasLocaleJson(dir: string): boolean {
  if (!existsSync(dir)) return false
  const names = readdirSync(dir, { withFileTypes: true })
  return names.some((e) => e.isFile() && e.name.endsWith('.json'))
}

/** True when each fixture has at least one dictionary JSON on disk (fresh clone check). */
export function localesArtifactsPresent(fixtures: PerfFixtureDef[]): boolean {
  return fixtures.every((fixture) => dirHasLocaleJson(fixtureSourceAbsDir(fixture)))
}

/**
 * Skip `generate:locales` when the runtime profile fingerprint is unchanged
 * **and** locale artifacts are present (avoids rewriting ~100MB+ dictionaries every run,
 * but still regenerates after a fresh clone where dictionaries are gitignored).
 */
export function ensurePerfLocales(profile: PerfRuntimeProfile, fixtures: PerfFixtureDef[]): void {
  const fp = profileFingerprint(profile)
  if (existsSync(LOCALE_FINGERPRINT) && localesArtifactsPresent(fixtures)) {
    try {
      const prev = readFileSync(LOCALE_FINGERPRINT, 'utf8').trim()
      if (prev === fp) {
        console.log('Locales unchanged (profile fingerprint match) — skip generate:locales')
        return
      }
    } catch {
      /* regenerate */
    }
  }
  regenerateLocales(fixtures)
  if (!existsSync(PERF_SHARED_DIR)) mkdirSync(PERF_SHARED_DIR, { recursive: true })
  writeFileSync(LOCALE_FINGERPRINT, `${fp}\n`, 'utf8')
}
